"""支撑工具模块。"""

from .branding import (
    append_branding_markdown,
    append_branding_text,
    attach_branding,
    build_brand_footer_markdown,
    build_brand_footer_text,
    build_branding_markdown,
    build_branding_text,
    build_disclaimer_markdown,
    build_disclaimer_text,
    get_branding_payload,
    get_disclaimer_payload,
    load_branding,
)
from .paths import (
    FATE_ASSET_ROOT,
    FATE_CONFIG_ROOT,
    FATE_CONTRACT_ROOT,
    FATE_DATA_ROOT,
    FATE_DATABASE_ROOT,
    FATE_PROFILE_DIR,
    FATE_REPO_ROOT,
    FATE_RUNTIME_ROOT,
    FATE_VENDOR_ROOT,
    TELEGRAM_SRC_DIR,
    TELEGRAM_START_SCRIPT,
    TELEGRAM_TRUE_SOLAR_TIME_JS,
)
from .timezone import CN_TZ, ensure_cn, fmt_cn, now_cn

__all__ = [
    "append_branding_markdown",
    "append_branding_text",
    "attach_branding",
    "build_brand_footer_markdown",
    "build_brand_footer_text",
    "build_branding_markdown",
    "build_branding_text",
    "build_disclaimer_markdown",
    "build_disclaimer_text",
    "FATE_ASSET_ROOT",
    "FATE_CONFIG_ROOT",
    "FATE_CONTRACT_ROOT",
    "FATE_DATA_ROOT",
    "FATE_DATABASE_ROOT",
    "FATE_PROFILE_DIR",
    "FATE_REPO_ROOT",
    "FATE_RUNTIME_ROOT",
    "FATE_VENDOR_ROOT",
    "TELEGRAM_SRC_DIR",
    "TELEGRAM_START_SCRIPT",
    "TELEGRAM_TRUE_SOLAR_TIME_JS",
    "CN_TZ",
    "ensure_cn",
    "fmt_cn",
    "get_branding_payload",
    "get_disclaimer_payload",
    "load_branding",
    "now_cn",
]
